In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
import sys
import time

In [2]:
url = "https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page={}"

In [3]:
titleList = []
priceList = []
ratingList = []
featureList = []
ratingsCountList = []
reviewsCountList = []

In [4]:
try:
  for i in range(1,4):
    print(url.format(i))
    req = requests.get(url.format(i))
    soup = BeautifulSoup(req.text, 'html.parser')
    itemsTable = soup.find('div', {'class':'_1YokD2 _3Mn1Gg'})
    cells = itemsTable.find_all('div', {'class':'_3pLy-c row'})
    
    for cell in cells:
    
        title = cell.find('div', {'class':'_4rR01T'})
        price = cell.find('div', {'class':'_30jeq3 _1_WHN1'})
        rating = cell.find('div', {'class':'_3LWZlK'})
        feature = cell.find('ul', {'class':'_1xgFaf'})
        ratingsCount = cell.find('span', {'class':'_2_R_DZ'})
    
        value = title.text if title.text != "" else ""
        titleList.append(value)

        value = price.text if price.text != "" else ""
        priceList.append(value)

        value = rating.text if rating.text != "" else ""
        ratingList.append(value)
        
        value = [] 
        if feature.text != "":
            for i in feature.text.split("|"):
                i = i.strip()
                value.append(i)
        featureList.append(value)

        value = []
        if ratingsCount.text != "":
            for i in ratingsCount.text.replace("Ratings","").replace("Reviews","").split("&"):
                value.append(int(i.replace(",","")))
        value0 = value[0] if len(value)==2 else 0
        value1 = value[1] if len(value)==2 else 0
        ratingsCountList.append(value0)
        reviewsCountList.append(value1)
        
except Exception as e:
  error_type, error_info, error_obj = sys.exec_info
  print("error in url", url)
  print(error_type, "line no:", error_info)

https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=3

In [5]:
df=pd.DataFrame({'title':titleList,'price':priceList, 'rating':ratingList, 'features':featureList,
                 'ratingCount':ratingsCountList, 'reviewsCount':reviewsCountList})
df

,title,price,rating,features,ratingCount,reviewsCount
0,"SAMSUNG Galaxy F13 (Waterfall Blue, 64 GB)","₹9,499",4.3,"[4 GB RAM, 64 GB ROM, Expandable Upto 1 TB16.7...",163123,9563
1,"SAMSUNG Galaxy F13 (Nightsky Green, 64 GB)","₹9,499",4.3,"[4 GB RAM, 64 GB ROM, Expandable Upto 1 TB16.7...",163123,9563
2,"APPLE iPhone 13 (Starlight, 128 GB)","₹57,999",4.7,[128 GB ROM15.49 cm (6.1 inch) Super Retina XD...,244100,12670
3,"POCO C51 (Power Black, 64 GB)","₹6,499",4.2,"[4 GB RAM, 64 GB ROM, Expandable Upto 1 TB16.5...",37049,1894
4,"POCO C51 (Royal Blue, 64 GB)","₹6,499",4.2,"[4 GB RAM, 64 GB ROM, Expandable Upto 1 TB16.5...",37049,1894
...,...,...,...,...,...,...
67,"MOTOROLA G32 (Satin Silver, 128 GB)","₹11,999",4.1,"[8 GB RAM, 128 GB ROM16.51 cm (6.5 inch) Full ...",38434,3288
68,"SAMSUNG Galaxy F23 5G (Copper Blush, 128 GB)","₹15,999",4.3,"[6 GB RAM, 128 GB ROM, Expandable Upto 1 TB16....",203019,15526
69,"APPLE iPhone 13 (Blue, 128 GB)","₹57,999",4.7,[128 GB ROM15.49 cm (6.1 inch) Super Retina XD...,244100,12219
70,Micromax J22,"₹1,115",3.9,"[32 MB RAM, 32 MB ROM6.1 cm (2.4 inch) Display...",2260,138
71,Micromax J22,"₹1,145",3.9,"[32 MB RAM, 32 MB ROM6.1 cm (2.4 inch) Display...",2260,138